name: CI pipeline
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout selected branch
        uses: actions/checkout@v4
      - name: Package application
        run: |
          zip -r app.zip . -x "*.git*"
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-package
          path: app.zip
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: beta
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: app-package
      - name: Copy ZIP to VM
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          source: "app.zip"
          target: "/home/jadmin/_work"

      - name: Extract application on VM
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd /home/jadmin/_work
            unzip -o app.zip
            rm app.zip
